### ISSUE TITLE
Extend MetricsParsers to handle incremental parsing

### ISSUE THREAD

**Issue by mcserep** [mcserep/CodeCompass#10]
Extend `MetricsParser` with a `maintain()` method and implement incremental parsing maintenance functionalities for the `Metrics` database table. `MetricsParser` should be dependent on `CppParser` if the latter manages the maintenance of the `File` entities.

Blocked by #9.

**Comment by intjftw** [comment]
Solved by 7affe0664a203876d61cce49066d458f21c009ef

**Comment by mcserep** [comment]
Minor fix in 02424ea456013225912b0124c24f7841f55d698c, since the `operator[]` will insert a new element into a map if the given key does not exist.
