### ISSUE TITLE
Refactor File Diagrams

### ISSUE THREAD

**Issue by mcserep** [mcserep/CodeCompass#11]
Refactor file diagram model and creation as already mentioned in #2.

- [x]  Open a new branch `filediagram_refactor` from `master`.
- [x]  The `CppNode` struct should be refactored, the only supported domain should be `FILE`. Therefore the `domain` field can be omitted, the `domainId` field can be `fileId` and its type should be `FileId` (`uint64_t`).
- [x]  The `RelationCollector` class should be refactored so that only file level relations (`USE` and `PROVIDE`) are created and persisted as `CppNode` and `CppEdge` entities. Accordingly the `CppEdge::Type` should be refactored and unused types (`DEPEND` and `IMPLEMENT`) can be omitted.
- [x]  Update the service component of the cppparser (`FileDiagram`), so that directory level relations are calculated and then visualized on-demand.
- [x] Since by this refactoring process, the `CppNode` type is simplified to only contain a file ID and the `CppNodeAttribute` type is unused, both of them can be eliminated entirely. Then the `CppEdge` type may connect 2 `File` entities instead of `CppNode`.

**Comment by mcserep** [comment]
Regarding the refactoring of the `FileDiagram` class, the `getImplementedFiles()` and `getDependFiles()` private methods should be modified, as more complex methods use them to retrieve the *IMPLEMENT* and *DEPENDS* relations between modules (directories).

As the result of the removal of the `model::CppEdge::IMPLEMENT` and the `model::CppEdge::DEPEND` enum values, these relations cannot be fetched directly from the database, but should be calculated on demand based on the stored file level *USE* and *PROVIDES* relations. The formal definitions of these relations are described in  sections 4.1 and 4.2 of [1] with example images.

The reuse of the `getProvidedFiles()` and the `getUsedFiles()` methods should be considered to avoid source code redundancy.

[1]  Cserép, Máté and Krupp, Dániel. Visualization Techniques of Components for Large Legacy C/C++ software. *Studia Universitatis Babes-Bolyai, Informatica*, pp. 59-74, 2014.  
http://www.cs.ubbcluj.ro/~studia-i/contents/2014-macs/05Cserep.pdf

**Comment by mcserep** [comment]
@intjftw: new follow-up objective added to the ticket, see description.

**Comment by mcserep** [comment]
@intjftw: while the `CppNode` type seems completely unused, it was not eliminated from the code base.

**Comment by intjftw** [comment]
@mcserep As far as I can remember I eliminated the CppNode type but I will take a look at it when I sync it with the master branch.
