### ISSUE TITLE
Refactor IncrementalStatus into ParserContext

### ISSUE THREAD

**Issue by mcserep** [mcserep/CodeCompass#8]
Currently the file status changes related to incremental parsing are calculated in `CppParser`. Since this information may be utilized by all plugin parsers, the enum type `IncrementalStatus` and the `std::unordered_map<std::string, IncrementalStatus>` map of file status changes defined in `CppParser` should be refactored into the `ParserContext` type, thus all plugin parsers will be able to query status changes related to incremental parsing.

**Comment by mcserep** [comment]
As decided on the Ericsson CodeCompass meeting today, the status detection of the files should be refactored into the `ParserContext`'s constructor. Detecting status changes based on the C++ header inclusion information should remain in the `CppParser`, as this information is specific and should only be used by that parser.

**Comment by intjftw** [comment]
Solved by Queen CPP
