### ISSUE TITLE
Generalize incremental parsing maintenance

### ISSUE THREAD

**Issue by mcserep** [mcserep/CodeCompass#9]
All plugin parsers should be able to perform maintenance operations related to incremental parsing.

- Extend the `AbstractParser` type with a `virtual void maintain() {}` method to support operations related to incremental parsing or other maintenance.
- Refactor the `incrementalParse()` method of the `CppParser` type into the parser's `maintain()` method.
- In `parser.cpp`, call the `maintain()` method for all parsers before calling the `parse()` method. The plugin parsers should be traversed in a reverse topological order, hence inverting the dependency relations defined between them for parsing.

Blocked by #8.

**Comment by mcserep** [comment]
As decided on the Ericsson CodeCompass meeting today, the `maintain()` method should be named `preparse()`. The `preparse()` method can read the file statuses from the `ParserContext` and decide to detect further status changes, e.g. through the C++ header inclusions (see #8). The `preparse()` is also responsible for the database maintenance as it was originally designed.

**Comment by intjftw** [comment]
Solved in 8f85585c03d2a23a25d25b9a4e301fe7aa24bf28
